/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/escalada-custo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Escalada Custo
         * @description Escalada de custo por contrato (mart_escalada_custo, spec 007/013/014).
         */
        get: operations["get_escalada_custo_api_v1_escalada_custo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diversidade-vencedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diversidade Vencedores
         * @description Diversidade de vencedores por processo licitatório (mart_diversidade_vencedores, spec 007). ano_inicio/ano_fim filtram por ano_abertura (ano de dt_primeiro_contrato, spec 029) — o grão continua sendo o processo, não período; processos multi-ano ficam atribuídos ao ano de abertura.
         */
        get: operations["get_diversidade_vencedores_api_v1_diversidade_vencedores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contratos-temporal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contratos Temporal
         * @description Série temporal de valor contratado (mart_contratos_temporal, spec 007/013).
         */
        get: operations["get_contratos_temporal_api_v1_contratos_temporal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concentracao-fornecedor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Concentracao Fornecedor
         * @description Concentração de gasto por fornecedor (mart_concentracao_fornecedor, spec 007/013/014/024/029). A mart tem grão (órgão, fornecedor, ano_assinatura) desde a spec 029 — rank/perc armazenados na mart só valem dentro de um único ano, então este endpoint sempre reagrega (SUM) e recalcula rank/perc no próprio SQL sobre o intervalo ano_inicio/ano_fim informado (ou sobre todo o histórico, se nenhum dos dois for informado — resultado idêntico ao grão antigo, pré-spec-029). Com cod_unidade_gestora informado, ordena e limita por rank_no_orgao recalculado. Sem cod_unidade_gestora, agrega por fornecedor somando todos os órgãos e ordena por rank_estado recalculado; cod_unidade_gestora/nm_unidade_gestora exibidos passam a ser o órgão de maior gasto do fornecedor dentro do intervalo (antes era um órgão arbitrário via DISTINCT ON).
         */
        get: operations["get_concentracao_fornecedor_api_v1_concentracao_fornecedor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgaos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Orgaos
         * @description Lista de órgãos (dim_orgaos, spec 007) — usada para popular filtro de órgão no frontend (sem ano_inicio/ano_fim) e para o gráfico de distribuição por perfil (com, spec 029). ano_inicio/ano_fim filtram órgãos por atividade — ao menos um contrato em fct_contratos dentro do intervalo — sem recalcular ds_perfil_contratacao, que continua histórico/acumulado. Sem os parâmetros, comportamento idêntico ao anterior à spec 029 (REQ-8).
         */
        get: operations["get_orgaos_api_v1_orgaos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modalidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Modalidades
         * @description Lista de modalidades de licitação (dim_modalidades, spec 007) — usada para popular filtro de modalidade no frontend, incluindo a categoria 'Não informado'.
         */
        get: operations["get_modalidades_api_v1_modalidades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qualidade-dado-orgao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qualidade Dado Orgao
         * @description Ranking de órgãos por qualidade de dado (spec 025) — agrega fl_aditivo_inconsistente/fl_valor_suspeito por cod_unidade_gestora direto no SQL sobre marts.mart_escalada_custo. As duas flags são a métrica aqui, não um filtro — nenhum contrato é excluído da contagem.
         */
        get: operations["get_qualidade_dado_orgao_api_v1_qualidade_dado_orgao_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variacao-custo-modalidade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Variacao Custo Modalidade
         * @description Variação de custo por modalidade (spec 025) — agrega perc_variacao por nm_modalidade_norm direto no SQL sobre marts.mart_escalada_custo. Considera só contratos com vl_variacao <> 0 (proxy de 'teve aditivo que mudou valor' — vl_aditado não é exposto pela mart, spec 013/014). Exclui contratos com fl_aditivo_inconsistente ou fl_valor_suspeito, mesmo critério do gráfico escalada-custo.
         */
        get: operations["get_variacao_custo_modalidade_api_v1_variacao_custo_modalidade_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variacao-prazo-modalidade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Variacao Prazo Modalidade
         * @description Variação de prazo por modalidade (spec 025) — agrega dias_variacao por nm_modalidade_norm direto no SQL sobre marts.mart_escalada_custo. Considera só contratos com dias_variacao <> 0 (proxy de 'teve aditivo que mudou prazo'). Exclui contratos com fl_aditivo_inconsistente ou fl_valor_suspeito, mesmo critério do gráfico escalada-custo.
         */
        get: operations["get_variacao_prazo_modalidade_api_v1_variacao_prazo_modalidade_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpis-resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kpis Resumo
         * @description KPIs resumo da home (spec 026) — agregado em 1 linha sobre marts.mart_escalada_custo. Sem campos de SUM de valor (valor_total/total_aditivos) — achado durante a spec 026: fl_valor_suspeito não cobre 13 contratos com |vl_variacao| > R$100mi (gap de detecção anterior à spec 021, não corrigido aqui), então qualquer SUM de vl_atual/vl_variacao fica sensível a um único outlier não sinalizado. Contagens (count) não são afetadas por esse gap — a classificação de um contrato como outlier não muda se ele é contado ou não.
         */
        get: operations["get_kpis_resumo_api_v1_kpis_resumo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfil-fornecedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Perfil Fornecedores
         * @description Distribuição de fornecedores por porte (spec 026) — GROUP BY porte_fornecedor sobre marts.dim_fornecedores; a classificação já vem pronta da mart (dim_fornecedores.sql), este endpoint só agrega o que já existe, não reclassifica nada. ano_inicio/ano_fim (spec 029) filtram fornecedores por atividade — ao menos um contrato em fct_contratos dentro do intervalo — sem recalcular porte_fornecedor, que continua histórico/acumulado.
         */
        get: operations["get_perfil_fornecedores_api_v1_perfil_fornecedores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConcentracaoFornecedor */
        ConcentracaoFornecedor: {
            /**
             * Cod Unidade Gestora
             * @description Código da unidade gestora
             */
            cod_unidade_gestora: string;
            /**
             * Nm Unidade Gestora
             * @description Nome da unidade gestora
             */
            nm_unidade_gestora?: string | null;
            /**
             * Id Contratado
             * @description Identificador do fornecedor. CNPJ exibido por completo; CPF já chega mascarado pela fonte (ex.: '***.006.069-**') — spec 012, achado 2026-08-20.
             */
            id_contratado: string;
            /**
             * Nm Contratado
             * @description Nome/razão social do fornecedor
             */
            nm_contratado?: string | null;
            /**
             * Ano Assinatura
             * @description Ano de assinatura (spec 029). Sem ano_inicio/ano_fim, este campo reflete o valor agregado no router (não corresponde a uma linha única da mart) — None nesse caso.
             */
            ano_assinatura?: number | null;
            /**
             * Vl Total Fornecedor Orgao
             * @description Soma de vl_atual dos contratos deste fornecedor com este órgão
             */
            vl_total_fornecedor_orgao?: string | null;
            /**
             * Vl Total Orgao
             * @description Soma de vl_atual de todos os fornecedores deste órgão
             */
            vl_total_orgao?: string | null;
            /**
             * Rank No Orgao
             * @description Ranking do fornecedor por gasto dentro do órgão (1 = maior)
             */
            rank_no_orgao?: number | null;
            /**
             * Perc Sobre Total Orgao
             * @description Percentual do gasto do órgão concentrado neste fornecedor
             */
            perc_sobre_total_orgao?: string | null;
            /**
             * Vl Total Fornecedor Estado
             * @description Soma de vl_atual de todos os contratos deste fornecedor, todos os órgãos
             */
            vl_total_fornecedor_estado?: string | null;
            /**
             * Vl Total Estado
             * @description Soma de vl_atual de todos os contratos do estado
             */
            vl_total_estado?: string | null;
            /**
             * Rank Estado
             * @description Ranking do fornecedor por gasto no estado inteiro
             */
            rank_estado?: number | null;
            /**
             * Perc Sobre Total Estado
             * @description Percentual do gasto total do estado concentrado neste fornecedor
             */
            perc_sobre_total_estado?: string | null;
        };
        /** ContratosTemporal */
        ContratosTemporal: {
            /**
             * Tp Recorte
             * @description Nível de recorte: 'Geral', 'Órgão' ou 'Modalidade'
             */
            tp_recorte: string;
            /**
             * Ano Assinatura
             * @description Ano de assinatura do contrato
             */
            ano_assinatura: number;
            /**
             * Mes Assinatura
             * @description Mês de assinatura do contrato
             */
            mes_assinatura: number;
            /**
             * Cod Unidade Gestora
             * @description Código da unidade gestora — preenchido só quando tp_recorte = 'Órgão'
             */
            cod_unidade_gestora?: string | null;
            /**
             * Nm Unidade Gestora
             * @description Nome da unidade gestora — preenchido só quando tp_recorte = 'Órgão'
             */
            nm_unidade_gestora?: string | null;
            /**
             * Nm Modalidade
             * @description Modalidade de licitação — preenchida só quando tp_recorte = 'Modalidade'
             */
            nm_modalidade?: string | null;
            /**
             * Qt Contratos
             * @description Quantidade de contratos no período/recorte
             */
            qt_contratos: number;
            /**
             * Vl Total Original
             * @description Soma dos valores originais no período/recorte
             */
            vl_total_original?: string | null;
            /**
             * Vl Total Atual
             * @description Soma dos valores atuais no período/recorte
             */
            vl_total_atual?: string | null;
            /**
             * Vl Total Variacao
             * @description Soma da variação no período/recorte
             */
            vl_total_variacao?: string | null;
            /**
             * Qt Contratos Acumulado Ano
             * @description Quantidade acumulada de contratos no ano até o mês — só em tp_recorte = 'Geral'
             */
            qt_contratos_acumulado_ano?: number | null;
            /**
             * Vl Acumulado Ano
             * @description Valor acumulado no ano até o mês — só em tp_recorte = 'Geral'
             */
            vl_acumulado_ano?: string | null;
            /**
             * Vl Mesmo Mes Ano Anterior
             * @description vl_total_atual do mesmo mês, ano-1, no mesmo recorte — null se não houver ano-1
             */
            vl_mesmo_mes_ano_anterior?: string | null;
            /**
             * Vl Variacao Ano Anterior
             * @description vl_total_atual - vl_mesmo_mes_ano_anterior — null se não houver ano-1
             */
            vl_variacao_ano_anterior?: string | null;
            /**
             * Perc Variacao Ano Anterior
             * @description Percentual de variação sobre o mesmo mês do ano anterior
             */
            perc_variacao_ano_anterior?: string | null;
            /**
             * Vl Media Movel 3Anos
             * @description Média de vl_total_atual dos últimos 3 anos-calendário para o mesmo mês/recorte
             */
            vl_media_movel_3anos?: string | null;
        };
        /** DiversidadeVencedores */
        DiversidadeVencedores: {
            /**
             * Cod Unidade Gestora
             * @description Código da unidade gestora
             */
            cod_unidade_gestora: string;
            /**
             * Nm Unidade Gestora
             * @description Nome da unidade gestora
             */
            nm_unidade_gestora?: string | null;
            /**
             * Nu Processo
             * @description Número do processo licitatório
             */
            nu_processo: string;
            /**
             * Qt Contratos
             * @description Quantidade de contratos vinculados a este processo
             */
            qt_contratos: number;
            /**
             * Qt Fornecedores Distintos
             * @description Quantidade de fornecedores distintos que venceram contratos deste processo
             */
            qt_fornecedores_distintos: number;
            /**
             * Qt Modalidades Distintas
             * @description Quantidade de modalidades distintas usadas nos contratos deste processo
             */
            qt_modalidades_distintas?: number | null;
            /**
             * Vl Total Original
             * @description Soma de vl_original dos contratos deste processo
             */
            vl_total_original?: string | null;
            /**
             * Vl Total Atual
             * @description Soma de vl_atual dos contratos deste processo
             */
            vl_total_atual?: string | null;
            /**
             * Vl Total Variacao
             * @description Soma de vl_variacao dos contratos deste processo
             */
            vl_total_variacao?: string | null;
            /**
             * Dt Primeiro Contrato
             * @description Data de assinatura do contrato mais antigo
             */
            dt_primeiro_contrato?: string | null;
            /**
             * Dt Ultimo Contrato
             * @description Data de assinatura do contrato mais recente
             */
            dt_ultimo_contrato?: string | null;
            /**
             * Ano Abertura
             * @description Ano de dt_primeiro_contrato — usado como filtro de ano do processo (spec 029)
             */
            ano_abertura?: number | null;
            /**
             * Ds Diversidade
             * @description Classificação: 'Fornecedor único' ou 'Múltiplos fornecedores'
             */
            ds_diversidade?: string | null;
            /**
             * Rank Por Diversidade
             * @description Ranking do processo por quantidade de fornecedores distintos (1 = mais diverso)
             */
            rank_por_diversidade?: number | null;
        };
        /** EscaladaCusto */
        EscaladaCusto: {
            /**
             * Cod Unidade Gestora
             * @description Código da unidade gestora
             */
            cod_unidade_gestora: string;
            /**
             * Nu Contrato
             * @description Número do contrato
             */
            nu_contrato: string;
            /**
             * Nm Unidade Gestora
             * @description Nome da unidade gestora
             */
            nm_unidade_gestora?: string | null;
            /**
             * Nm Modalidade
             * @description Modalidade de licitação (valor bruto da fonte)
             */
            nm_modalidade?: string | null;
            /**
             * Ano Assinatura
             * @description Ano de assinatura do contrato
             */
            ano_assinatura?: number | null;
            /**
             * Mes Assinatura
             * @description Mês de assinatura do contrato
             */
            mes_assinatura?: number | null;
            /**
             * Dt Assinatura
             * @description Data de assinatura do contrato
             */
            dt_assinatura?: string | null;
            /**
             * Id Contratado
             * @description Identificador do fornecedor (CNPJ ou CPF pré-mascarado pela fonte)
             */
            id_contratado: string;
            /**
             * Nm Contratado
             * @description Nome/razão social do fornecedor
             */
            nm_contratado?: string | null;
            /**
             * Vl Original
             * @description Valor original do contrato
             */
            vl_original?: string | null;
            /**
             * Vl Atual
             * @description Valor atual do contrato
             */
            vl_atual?: string | null;
            /**
             * Vl Variacao
             * @description Escalada de custo — métrica oficial (vl_atual - vl_original), spec 013/014
             */
            vl_variacao?: string | null;
            /**
             * Perc Variacao
             * @description Percentual de variação sobre vl_original
             */
            perc_variacao?: string | null;
            /**
             * Dias Originais
             * @description Prazo original em dias
             */
            dias_originais?: number | null;
            /**
             * Dias Atuais
             * @description Prazo atual em dias
             */
            dias_atuais?: number | null;
            /**
             * Dias Variacao
             * @description Variação de prazo em dias
             */
            dias_variacao?: number | null;
            /**
             * Tp Variacao
             * @description Classificação da variação de valor
             */
            tp_variacao?: string | null;
            /**
             * Fl Aditivo Inconsistente
             * @description Sinal de qualidade de dado (spec 013/014): true quando vl_aditado diverge de vl_variacao
             */
            fl_aditivo_inconsistente?: boolean | null;
            /**
             * Fl Valor Suspeito
             * @description Sinal de valor implausível em vl_original/vl_atual (spec 021): três padrões de corrupção de valor, ver mart
             */
            fl_valor_suspeito?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KpisResumo */
        KpisResumo: {
            /**
             * Total Contratos
             * @description Total de contratos
             */
            total_contratos: number;
            /**
             * Fornecedores Distintos
             * @description Quantidade de fornecedores distintos
             */
            fornecedores_distintos: number;
            /**
             * Orgaos Distintos
             * @description Quantidade de órgãos distintos
             */
            orgaos_distintos: number;
            /**
             * Contratos Com Aditivo
             * @description Quantidade de contratos com vl_variacao <> 0
             */
            contratos_com_aditivo: number;
        };
        /** Modalidade */
        Modalidade: {
            /**
             * Nm Modalidade
             * @description Nome da modalidade de licitação
             */
            nm_modalidade: string;
            /**
             * Qt Contratos
             * @description Total de contratos na modalidade
             */
            qt_contratos: number;
            /**
             * Qt Orgaos Distintos
             * @description Quantidade de órgãos distintos que usaram a modalidade
             */
            qt_orgaos_distintos?: number | null;
            /**
             * Qt Fornecedores Distintos
             * @description Quantidade de fornecedores distintos na modalidade
             */
            qt_fornecedores_distintos?: number | null;
            /**
             * Vl Total Original
             * @description Soma dos valores originais
             */
            vl_total_original?: string | null;
            /**
             * Vl Total Atual
             * @description Soma dos valores atuais
             */
            vl_total_atual?: string | null;
            /**
             * Vl Total Aditado
             * @description Soma dos valores de aditivo
             */
            vl_total_aditado?: string | null;
            /**
             * Vl Total Variacao
             * @description Soma da variação total
             */
            vl_total_variacao?: string | null;
            /**
             * Vl Medio Contrato
             * @description Valor médio dos contratos
             */
            vl_medio_contrato?: string | null;
            /**
             * Vl Maior Contrato
             * @description Valor do maior contrato
             */
            vl_maior_contrato?: string | null;
            /**
             * Vl Menor Contrato
             * @description Valor do menor contrato
             */
            vl_menor_contrato?: string | null;
            /**
             * Perc Contratos Com Aditivo
             * @description Percentual de contratos que tiveram aditivo
             */
            perc_contratos_com_aditivo?: string | null;
            /**
             * Rank Por Quantidade
             * @description Ranking por quantidade de contratos
             */
            rank_por_quantidade?: number | null;
            /**
             * Rank Por Valor
             * @description Ranking por valor total
             */
            rank_por_valor?: number | null;
            /**
             * Perc Sobre Total Qt
             * @description Percentual da modalidade sobre o total de contratos
             */
            perc_sobre_total_qt?: string | null;
            /**
             * Perc Sobre Total Valor
             * @description Percentual da modalidade sobre o valor total
             */
            perc_sobre_total_valor?: string | null;
        };
        /** Orgao */
        Orgao: {
            /**
             * Cod Unidade Gestora
             * @description Código da unidade gestora
             */
            cod_unidade_gestora: string;
            /**
             * Nm Unidade Gestora
             * @description Nome da unidade gestora
             */
            nm_unidade_gestora: string;
            /**
             * Cod Gestao
             * @description Código da gestão
             */
            cod_gestao?: string | null;
            /**
             * Nm Gestao
             * @description Nome da gestão
             */
            nm_gestao?: string | null;
            /**
             * Qt Contratos
             * @description Total de contratos do órgão
             */
            qt_contratos: number;
            /**
             * Qt Fornecedores Distintos
             * @description Quantidade de fornecedores distintos contratados
             */
            qt_fornecedores_distintos?: number | null;
            /**
             * Vl Total Original
             * @description Soma dos valores originais
             */
            vl_total_original?: string | null;
            /**
             * Vl Total Atual
             * @description Soma dos valores atuais
             */
            vl_total_atual?: string | null;
            /**
             * Vl Total Aditado
             * @description Soma dos valores de aditivo
             */
            vl_total_aditado?: string | null;
            /**
             * Vl Total Variacao
             * @description Soma da variação total
             */
            vl_total_variacao?: string | null;
            /**
             * Vl Medio Contrato
             * @description Valor médio dos contratos
             */
            vl_medio_contrato?: string | null;
            /**
             * Vl Maior Contrato
             * @description Valor do maior contrato
             */
            vl_maior_contrato?: string | null;
            /**
             * Vl Menor Contrato
             * @description Valor do menor contrato
             */
            vl_menor_contrato?: string | null;
            /**
             * Dt Primeiro Contrato
             * @description Data do primeiro contrato
             */
            dt_primeiro_contrato?: string | null;
            /**
             * Dt Ultimo Contrato
             * @description Data do último contrato
             */
            dt_ultimo_contrato?: string | null;
            /**
             * Rank Por Valor
             * @description Ranking do órgão por valor total contratado
             */
            rank_por_valor?: number | null;
            /**
             * Rank Por Quantidade
             * @description Ranking do órgão por quantidade de contratos
             */
            rank_por_quantidade?: number | null;
            /**
             * Ds Situacao Aditivo
             * @description Classificação textual da situação de aditivo do órgão
             */
            ds_situacao_aditivo?: string | null;
            /**
             * Ds Perfil Contratacao
             * @description Classificação textual do perfil de contratação do órgão
             */
            ds_perfil_contratacao?: string | null;
        };
        /** PerfilFornecedores */
        PerfilFornecedores: {
            /**
             * Porte Fornecedor
             * @description Classificação por porte: Micro, Pequeno, Médio, Grande
             */
            porte_fornecedor: string;
            /**
             * Qt Fornecedores
             * @description Quantidade de fornecedores na faixa
             */
            qt_fornecedores: number;
            /**
             * Valor Total
             * @description Soma de vl_total_atual dos fornecedores na faixa
             */
            valor_total?: string | null;
        };
        /** QualidadeDadoOrgao */
        QualidadeDadoOrgao: {
            /**
             * Cod Unidade Gestora
             * @description Código da unidade gestora
             */
            cod_unidade_gestora: string;
            /**
             * Nm Unidade Gestora
             * @description Nome da unidade gestora
             */
            nm_unidade_gestora?: string | null;
            /**
             * Qt Contratos
             * @description Total de contratos do órgão em mart_escalada_custo
             */
            qt_contratos: number;
            /**
             * Qt Aditivo Inconsistente
             * @description Quantidade de contratos com fl_aditivo_inconsistente = true
             */
            qt_aditivo_inconsistente: number;
            /**
             * Perc Aditivo Inconsistente
             * @description Percentual de contratos com fl_aditivo_inconsistente = true
             */
            perc_aditivo_inconsistente: string;
            /**
             * Qt Valor Suspeito
             * @description Quantidade de contratos com fl_valor_suspeito = true
             */
            qt_valor_suspeito: number;
            /**
             * Perc Valor Suspeito
             * @description Percentual de contratos com fl_valor_suspeito = true
             */
            perc_valor_suspeito: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariacaoCustoModalidade */
        VariacaoCustoModalidade: {
            /**
             * Nm Modalidade
             * @description Modalidade de licitação normalizada (nm_modalidade_norm, spec 025)
             */
            nm_modalidade: string;
            /**
             * Qt Contratos Com Aditivo
             * @description Quantidade de contratos com vl_variacao <> 0, excluindo fl_aditivo_inconsistente/fl_valor_suspeito
             */
            qt_contratos_com_aditivo: number;
            /**
             * Perc Variacao Media
             * @description Média de perc_variacao entre os contratos com aditivo de valor
             */
            perc_variacao_media: string;
        };
        /** VariacaoPrazoModalidade */
        VariacaoPrazoModalidade: {
            /**
             * Nm Modalidade
             * @description Modalidade de licitação normalizada (nm_modalidade_norm, spec 025)
             */
            nm_modalidade: string;
            /**
             * Qt Contratos Com Aditivo Prazo
             * @description Quantidade de contratos com dias_variacao <> 0, excluindo fl_aditivo_inconsistente/fl_valor_suspeito
             */
            qt_contratos_com_aditivo_prazo: number;
            /**
             * Dias Variacao Media
             * @description Média de dias_variacao entre os contratos com aditivo de prazo
             */
            dias_variacao_media: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_escalada_custo_api_v1_escalada_custo_get: {
        parameters: {
            query?: {
                /** @description Código da unidade gestora */
                cod_unidade_gestora?: string | null;
                /** @description Modalidade de licitação */
                nm_modalidade?: string | null;
                /** @description Ano de assinatura do contrato */
                ano?: number | null;
                /** @description Teto de segurança — não é paginação. O frontend consome o dataset completo (grão é contrato, 1:1 com raw.contratos); volume real em dev é ~76041 linhas, teto de raw.contratos confirmado em 95508 linhas (spec 019, 2026-08-21). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscaladaCusto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diversidade_vencedores_api_v1_diversidade_vencedores_get: {
        parameters: {
            query?: {
                /** @description Código da unidade gestora */
                cod_unidade_gestora?: string | null;
                /** @description Ano inicial de ano_abertura (inclusive) */
                ano_inicio?: number | null;
                /** @description Ano final de ano_abertura (inclusive) */
                ano_fim?: number | null;
                /** @description Teto de segurança — não é paginação. O frontend consome o dataset completo (grão é processo, não é 'top N'); volume real em staging é ~51812 linhas (2026-08-21). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiversidadeVencedores"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contratos_temporal_api_v1_contratos_temporal_get: {
        parameters: {
            query?: {
                /** @description Código da unidade gestora */
                cod_unidade_gestora?: string | null;
                /** @description Modalidade de licitação */
                nm_modalidade?: string | null;
                /** @description Ano inicial do período (inclusive) */
                ano_inicio?: number | null;
                /** @description Ano final do período (inclusive) */
                ano_fim?: number | null;
                /** @description Teto de segurança — não é paginação. O frontend consome a série completa (agregado, não é 'top N'); volume real em staging é ~10810 linhas (2026-08-21). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratosTemporal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_concentracao_fornecedor_api_v1_concentracao_fornecedor_get: {
        parameters: {
            query?: {
                /** @description Código da unidade gestora */
                cod_unidade_gestora?: string | null;
                /** @description Ano inicial de ano_assinatura (inclusive) */
                ano_inicio?: number | null;
                /** @description Ano final de ano_assinatura (inclusive) */
                ano_fim?: number | null;
                /** @description Quantidade máxima de fornecedores retornados */
                top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConcentracaoFornecedor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orgaos_api_v1_orgaos_get: {
        parameters: {
            query?: {
                /** @description Ano inicial de atividade (inclusive) */
                ano_inicio?: number | null;
                /** @description Ano final de atividade (inclusive) */
                ano_fim?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Orgao"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_modalidades_api_v1_modalidades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Modalidade"][];
                };
            };
        };
    };
    get_qualidade_dado_orgao_api_v1_qualidade_dado_orgao_get: {
        parameters: {
            query?: {
                /** @description Ano inicial do período (inclusive) */
                ano_inicio?: number | null;
                /** @description Ano final do período (inclusive) */
                ano_fim?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualidadeDadoOrgao"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_variacao_custo_modalidade_api_v1_variacao_custo_modalidade_get: {
        parameters: {
            query?: {
                /** @description Ano inicial do período (inclusive) */
                ano_inicio?: number | null;
                /** @description Ano final do período (inclusive) */
                ano_fim?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariacaoCustoModalidade"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_variacao_prazo_modalidade_api_v1_variacao_prazo_modalidade_get: {
        parameters: {
            query?: {
                /** @description Ano inicial do período (inclusive) */
                ano_inicio?: number | null;
                /** @description Ano final do período (inclusive) */
                ano_fim?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariacaoPrazoModalidade"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kpis_resumo_api_v1_kpis_resumo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpisResumo"];
                };
            };
        };
    };
    get_perfil_fornecedores_api_v1_perfil_fornecedores_get: {
        parameters: {
            query?: {
                /** @description Ano inicial de atividade (inclusive) */
                ano_inicio?: number | null;
                /** @description Ano final de atividade (inclusive) */
                ano_fim?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilFornecedores"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
